--- 
services: 
  web:
    build:
      context: .
      dockerfile: django/Dockerfile
    command: "python ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - "db"
    ports: 
      - "8000:8000"
    volumes: 
      - "./django:/data"
    environment:
      DATABASE_URL: "postgres://postgres@db/postgres"

  ember:
    build:
      context: .
      dockerfile: ember/Dockerfile
    #command: ember server --live-reload-port 35730
    entrypoint: /usr/src/app/development-entrypoint

    volumes:
      - "./ember:/usr/src/app"
    stdin_open: true
    tty: true

    ports:
      - 4200:4200
      - 35730:35730
    environment:
      SOME_URL: whatever

  db:
    image: "postgres:9.6"
version: "2"

