--- 
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - "db"
    ports: 
      - "8000:8000"
    volumes: 
      - ".:/data"
    environment:
      DATABASE_URL: "postgres://postgres@db/postgres"

  db:
    image: "postgres:9.6"
version: "2"

